### ISSUE TITLE
Need to merge everyone back to master

### ISSUE THREAD

**Issue by mr-nati** [dynamiclogic/tams-android#4]
We've got 8 branches apart from master...we should be branching for a feature then merging it back in with a Pull Request.

**Comment by nati22** [comment]
We've got 8 branches off of master...we should be branching for a feature then merging it back in with a Pull Request.

**Comment by mr-nati** [comment]
The repo has been cleaned up as far as files that shouldn't be committed and map keys have been sorted out. We should be fine to keep working on our branches from here on out. It would be great if we didn't stay apart from master for too many commits though.
